---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: sharing-demo
  name: sharing-demo-job
spec:
  parallelism: 4
  backoffLimit: 100
  template:
    spec:
      restartPolicy: OnFailure
      resourceClaims:
      - name: gpu-ts-sharing
        source:
          resourceClaimName: gpu-ts-sharing
      - name: gpu-mps-sharing
        source:
          resourceClaimName: gpu-mps-sharing
      - name: mig-ts-sharing
        source:
          resourceClaimName: mig-ts-sharing
      - name: mig-mps-sharing
        source:
          resourceClaimName: mig-mps-sharing
      containers:
      - name: gpu-ts-sharing-ctr
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
        args: ["--benchmark", "--numbodies=4226048"]
        resources:
          claims:
          - name: gpu-ts-sharing
      - name: gpu-mps-sharing-ctr
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
        args: ["--benchmark", "--numbodies=4226048"]
        resources:
          claims:
          - name: gpu-mps-sharing
      - name: mig-ts-sharing-ctr
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
        args: ["--benchmark", "--numbodies=4226048"]
        resources:
          claims:
          - name: mig-ts-sharing
      - name: mig-mps-sharing-ctr
        image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
        args: ["--benchmark", "--numbodies=4226048"]
        resources:
          claims:
          - name: mig-mps-sharing
