---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-dra-driver.fullname" . }}-role-binding
  namespace: {{ include "k8s-dra-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-dra-driver.serviceAccountName" . }}
  namespace: {{ include "k8s-dra-driver.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "k8s-dra-driver.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
