/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/NVIDIA/k8s-dra-driver-gpu/api/nvidia.com/resource/v1beta1"
	scheme "github.com/NVIDIA/k8s-dra-driver-gpu/pkg/nvidia.com/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ComputeDomainsGetter has a method to return a ComputeDomainInterface.
// A group's client should implement this interface.
type ComputeDomainsGetter interface {
	ComputeDomains(namespace string) ComputeDomainInterface
}

// ComputeDomainInterface has methods to work with ComputeDomain resources.
type ComputeDomainInterface interface {
	Create(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.CreateOptions) (*v1beta1.ComputeDomain, error)
	Update(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.UpdateOptions) (*v1beta1.ComputeDomain, error)
	UpdateStatus(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.UpdateOptions) (*v1beta1.ComputeDomain, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ComputeDomain, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ComputeDomainList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomain, err error)
	ComputeDomainExpansion
}

// computeDomains implements ComputeDomainInterface
type computeDomains struct {
	client rest.Interface
	ns     string
}

// newComputeDomains returns a ComputeDomains
func newComputeDomains(c *ResourceV1beta1Client, namespace string) *computeDomains {
	return &computeDomains{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the computeDomain, and returns the corresponding computeDomain object, and an error if there is any.
func (c *computeDomains) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomain, err error) {
	result = &v1beta1.ComputeDomain{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomains").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ComputeDomains that match those selectors.
func (c *computeDomains) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ComputeDomainList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested computeDomains.
func (c *computeDomains) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("computedomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a computeDomain and creates it.  Returns the server's representation of the computeDomain, and an error, if there is any.
func (c *computeDomains) Create(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.CreateOptions) (result *v1beta1.ComputeDomain, err error) {
	result = &v1beta1.ComputeDomain{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("computedomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomain).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a computeDomain and updates it. Returns the server's representation of the computeDomain, and an error, if there is any.
func (c *computeDomains) Update(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.UpdateOptions) (result *v1beta1.ComputeDomain, err error) {
	result = &v1beta1.ComputeDomain{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("computedomains").
		Name(computeDomain.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomain).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *computeDomains) UpdateStatus(ctx context.Context, computeDomain *v1beta1.ComputeDomain, opts v1.UpdateOptions) (result *v1beta1.ComputeDomain, err error) {
	result = &v1beta1.ComputeDomain{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("computedomains").
		Name(computeDomain.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomain).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the computeDomain and deletes it. Returns an error if one occurs.
func (c *computeDomains) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomains").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *computeDomains) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomains").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched computeDomain.
func (c *computeDomains) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomain, err error) {
	result = &v1beta1.ComputeDomain{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("computedomains").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
