# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# main branch
  - package-ecosystem: "gomod"
    target-branch: main
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
    - dependency-name: k8s.io/*
    labels:
    - dependencies

  - package-ecosystem: "docker"
    target-branch: main
    directories:
    # CUDA image
    - "/deployments/container"
    # Golang version
    - "/deployments/devel"
    schedule:
      interval: "daily"
    labels:
    - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
