# Two pods, one container each
# Each container asking for 2 distinct GPUs

apiVersion: dra.gpu.nvidia.com/v1
kind: GpuClaim
metadata:
  name: gpu-example1-test-parameters
spec:
  count: 2

---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-example1-test1
spec:
  restartPolicy: Never
  containers:
  - name: ctr
    image: ubuntu:22.04
    command: ["sleep", "99999"]
    resources:
      claims:
      - gpus
  resourceClaims:
  - name: gpus
    claim:
      template:
        spec:
          resourceClassName: gpu.nvidia.com
          parameters:
            apiVersion: dra.gpu.nvidia.com/v1
            kind: GpuClaim
            name: gpu-example1-test-parameters

---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-example1-test2
spec:
  restartPolicy: Never
  containers:
  - name: ctr
    image: ubuntu:22.04
    command: ["sleep", "99999"]
    resources:
      claims:
      - gpus
  resourceClaims:
  - name: gpus
    claim:
      template:
        spec:
          resourceClassName: gpu.nvidia.com
          parameters:
            apiVersion: dra.gpu.nvidia.com/v1
            kind: GpuClaim
            name: gpu-example1-test-parameters
