/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/clientset/versioned/scheme"
	v1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DeviceClassParametersGetter has a method to return a DeviceClassParametersInterface.
// A group's client should implement this interface.
type DeviceClassParametersGetter interface {
	DeviceClassParameters() DeviceClassParametersInterface
}

// DeviceClassParametersInterface has methods to work with DeviceClassParameters resources.
type DeviceClassParametersInterface interface {
	Create(ctx context.Context, deviceClassParameters *v1.DeviceClassParameters, opts metav1.CreateOptions) (*v1.DeviceClassParameters, error)
	Update(ctx context.Context, deviceClassParameters *v1.DeviceClassParameters, opts metav1.UpdateOptions) (*v1.DeviceClassParameters, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DeviceClassParameters, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DeviceClassParametersList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DeviceClassParameters, err error)
	DeviceClassParametersExpansion
}

// deviceClassParameters implements DeviceClassParametersInterface
type deviceClassParameters struct {
	client rest.Interface
}

// newDeviceClassParameters returns a DeviceClassParameters
func newDeviceClassParameters(c *DraV1Client) *deviceClassParameters {
	return &deviceClassParameters{
		client: c.RESTClient(),
	}
}

// Get takes name of the deviceClassParameters, and returns the corresponding deviceClassParameters object, and an error if there is any.
func (c *deviceClassParameters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DeviceClassParameters, err error) {
	result = &v1.DeviceClassParameters{}
	err = c.client.Get().
		Resource("deviceclassparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DeviceClassParameters that match those selectors.
func (c *deviceClassParameters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DeviceClassParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DeviceClassParametersList{}
	err = c.client.Get().
		Resource("deviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested deviceClassParameters.
func (c *deviceClassParameters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("deviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a deviceClassParameters and creates it.  Returns the server's representation of the deviceClassParameters, and an error, if there is any.
func (c *deviceClassParameters) Create(ctx context.Context, deviceClassParameters *v1.DeviceClassParameters, opts metav1.CreateOptions) (result *v1.DeviceClassParameters, err error) {
	result = &v1.DeviceClassParameters{}
	err = c.client.Post().
		Resource("deviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a deviceClassParameters and updates it. Returns the server's representation of the deviceClassParameters, and an error, if there is any.
func (c *deviceClassParameters) Update(ctx context.Context, deviceClassParameters *v1.DeviceClassParameters, opts metav1.UpdateOptions) (result *v1.DeviceClassParameters, err error) {
	result = &v1.DeviceClassParameters{}
	err = c.client.Put().
		Resource("deviceclassparameters").
		Name(deviceClassParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the deviceClassParameters and deletes it. Returns an error if one occurs.
func (c *deviceClassParameters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("deviceclassparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *deviceClassParameters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("deviceclassparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched deviceClassParameters.
func (c *deviceClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DeviceClassParameters, err error) {
	result = &v1.DeviceClassParameters{}
	err = c.client.Patch(pt).
		Resource("deviceclassparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
