/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/clientset/versioned/scheme"
	v1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DeviceClassesGetter has a method to return a DeviceClassInterface.
// A group's client should implement this interface.
type DeviceClassesGetter interface {
	DeviceClasses() DeviceClassInterface
}

// DeviceClassInterface has methods to work with DeviceClass resources.
type DeviceClassInterface interface {
	Create(ctx context.Context, deviceClass *v1.DeviceClass, opts metav1.CreateOptions) (*v1.DeviceClass, error)
	Update(ctx context.Context, deviceClass *v1.DeviceClass, opts metav1.UpdateOptions) (*v1.DeviceClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DeviceClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DeviceClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DeviceClass, err error)
	DeviceClassExpansion
}

// deviceClasses implements DeviceClassInterface
type deviceClasses struct {
	client rest.Interface
}

// newDeviceClasses returns a DeviceClasses
func newDeviceClasses(c *DraV1Client) *deviceClasses {
	return &deviceClasses{
		client: c.RESTClient(),
	}
}

// Get takes name of the deviceClass, and returns the corresponding deviceClass object, and an error if there is any.
func (c *deviceClasses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DeviceClass, err error) {
	result = &v1.DeviceClass{}
	err = c.client.Get().
		Resource("deviceclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DeviceClasses that match those selectors.
func (c *deviceClasses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DeviceClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DeviceClassList{}
	err = c.client.Get().
		Resource("deviceclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested deviceClasses.
func (c *deviceClasses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("deviceclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a deviceClass and creates it.  Returns the server's representation of the deviceClass, and an error, if there is any.
func (c *deviceClasses) Create(ctx context.Context, deviceClass *v1.DeviceClass, opts metav1.CreateOptions) (result *v1.DeviceClass, err error) {
	result = &v1.DeviceClass{}
	err = c.client.Post().
		Resource("deviceclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceClass).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a deviceClass and updates it. Returns the server's representation of the deviceClass, and an error, if there is any.
func (c *deviceClasses) Update(ctx context.Context, deviceClass *v1.DeviceClass, opts metav1.UpdateOptions) (result *v1.DeviceClass, err error) {
	result = &v1.DeviceClass{}
	err = c.client.Put().
		Resource("deviceclasses").
		Name(deviceClass.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceClass).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the deviceClass and deletes it. Returns an error if one occurs.
func (c *deviceClasses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("deviceclasses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *deviceClasses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("deviceclasses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched deviceClass.
func (c *deviceClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DeviceClass, err error) {
	result = &v1.DeviceClass{}
	err = c.client.Patch(pt).
		Resource("deviceclasses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
