/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/clientset/versioned/scheme"
	v1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MigDeviceClaimsGetter has a method to return a MigDeviceClaimInterface.
// A group's client should implement this interface.
type MigDeviceClaimsGetter interface {
	MigDeviceClaims(namespace string) MigDeviceClaimInterface
}

// MigDeviceClaimInterface has methods to work with MigDeviceClaim resources.
type MigDeviceClaimInterface interface {
	Create(ctx context.Context, migDeviceClaim *v1.MigDeviceClaim, opts metav1.CreateOptions) (*v1.MigDeviceClaim, error)
	Update(ctx context.Context, migDeviceClaim *v1.MigDeviceClaim, opts metav1.UpdateOptions) (*v1.MigDeviceClaim, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MigDeviceClaim, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MigDeviceClaimList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MigDeviceClaim, err error)
	MigDeviceClaimExpansion
}

// migDeviceClaims implements MigDeviceClaimInterface
type migDeviceClaims struct {
	client rest.Interface
	ns     string
}

// newMigDeviceClaims returns a MigDeviceClaims
func newMigDeviceClaims(c *DraV1Client, namespace string) *migDeviceClaims {
	return &migDeviceClaims{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the migDeviceClaim, and returns the corresponding migDeviceClaim object, and an error if there is any.
func (c *migDeviceClaims) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MigDeviceClaim, err error) {
	result = &v1.MigDeviceClaim{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MigDeviceClaims that match those selectors.
func (c *migDeviceClaims) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MigDeviceClaimList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MigDeviceClaimList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested migDeviceClaims.
func (c *migDeviceClaims) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a migDeviceClaim and creates it.  Returns the server's representation of the migDeviceClaim, and an error, if there is any.
func (c *migDeviceClaims) Create(ctx context.Context, migDeviceClaim *v1.MigDeviceClaim, opts metav1.CreateOptions) (result *v1.MigDeviceClaim, err error) {
	result = &v1.MigDeviceClaim{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(migDeviceClaim).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a migDeviceClaim and updates it. Returns the server's representation of the migDeviceClaim, and an error, if there is any.
func (c *migDeviceClaims) Update(ctx context.Context, migDeviceClaim *v1.MigDeviceClaim, opts metav1.UpdateOptions) (result *v1.MigDeviceClaim, err error) {
	result = &v1.MigDeviceClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		Name(migDeviceClaim.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(migDeviceClaim).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the migDeviceClaim and deletes it. Returns an error if one occurs.
func (c *migDeviceClaims) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *migDeviceClaims) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migdeviceclaims").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched migDeviceClaim.
func (c *migDeviceClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MigDeviceClaim, err error) {
	result = &v1.MigDeviceClaim{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("migdeviceclaims").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
