# Run as a deployment with 4 replicas
# Each replica shares a mig-enabled GPU using Time-Slicing

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test6

---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test6
  name: mig-devices
spec:
  spec:
    devices:
      requests:
      - name: mig-1g-5gb
        deviceClassName: mig.nvidia.com
        selectors:
        - cel:
            expression: "device.attributes['gpu.nvidia.com'].profile == '1g.5gb'"
      config:
      - requests: ["mig-1g-5gb"]
        opaque:
          driver: mig.nvidia.com
          parameters:
            apiVersion: gpu.nvidia.com/v1alpha1
            kind: GpuConfig
            sharing:
              strategy: TimeSlicing
              timeSlicingConfig:
                interval: Long
      constraints:
      - requests: []
        matchAttribute: "gpu.nvidia.com/parentUUID"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpu-test6
  name: pod
  labels:
    app: gpu-test6-pod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      resourceClaims:
      - name: mig-ts-gpu
        resourceClaimTemplateName: mig-devices
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: mig-ts-gpu
            request: mig-1g-5gb
