//go:build !ignore_autogenerated

/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomain) DeepCopyInto(out *ComputeDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomain.
func (in *ComputeDomain) DeepCopy() *ComputeDomain {
	if in == nil {
		return nil
	}
	out := new(ComputeDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainList) DeepCopyInto(out *ComputeDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainList.
func (in *ComputeDomainList) DeepCopy() *ComputeDomainList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainNode) DeepCopyInto(out *ComputeDomainNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainNode.
func (in *ComputeDomainNode) DeepCopy() *ComputeDomainNode {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainNodeAffinity) DeepCopyInto(out *ComputeDomainNodeAffinity) {
	*out = *in
	if in.Preferred != nil {
		in, out := &in.Preferred, &out.Preferred
		*out = make([]v1.PreferredSchedulingTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainNodeAffinity.
func (in *ComputeDomainNodeAffinity) DeepCopy() *ComputeDomainNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainSpec) DeepCopyInto(out *ComputeDomainSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(ComputeDomainNodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyAlignment != nil {
		in, out := &in.TopologyAlignment, &out.TopologyAlignment
		*out = new(ComputeDomainTopologyAlignment)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyAntiAlignment != nil {
		in, out := &in.TopologyAntiAlignment, &out.TopologyAntiAlignment
		*out = new(ComputeDomainTopologyAlignment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainSpec.
func (in *ComputeDomainSpec) DeepCopy() *ComputeDomainSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainStatus) DeepCopyInto(out *ComputeDomainStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]*ComputeDomainNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ComputeDomainNode)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainStatus.
func (in *ComputeDomainStatus) DeepCopy() *ComputeDomainStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainTopologyAlignment) DeepCopyInto(out *ComputeDomainTopologyAlignment) {
	*out = *in
	if in.Preferred != nil {
		in, out := &in.Preferred, &out.Preferred
		*out = make([]ComputeDomainWeightedTopologyKey, len(*in))
		copy(*out, *in)
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(ComputeDomainTopologyKeys)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainTopologyAlignment.
func (in *ComputeDomainTopologyAlignment) DeepCopy() *ComputeDomainTopologyAlignment {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainTopologyAlignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainTopologyKeys) DeepCopyInto(out *ComputeDomainTopologyKeys) {
	*out = *in
	if in.TopologyKeys != nil {
		in, out := &in.TopologyKeys, &out.TopologyKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainTopologyKeys.
func (in *ComputeDomainTopologyKeys) DeepCopy() *ComputeDomainTopologyKeys {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainTopologyKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainWeightedTopologyKey) DeepCopyInto(out *ComputeDomainWeightedTopologyKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainWeightedTopologyKey.
func (in *ComputeDomainWeightedTopologyKey) DeepCopy() *ComputeDomainWeightedTopologyKey {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainWeightedTopologyKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuConfig) DeepCopyInto(out *GpuConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(GpuSharing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuConfig.
func (in *GpuConfig) DeepCopy() *GpuConfig {
	if in == nil {
		return nil
	}
	out := new(GpuConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuSharing) DeepCopyInto(out *GpuSharing) {
	*out = *in
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MpsConfig != nil {
		in, out := &in.MpsConfig, &out.MpsConfig
		*out = new(MpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuSharing.
func (in *GpuSharing) DeepCopy() *GpuSharing {
	if in == nil {
		return nil
	}
	out := new(GpuSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImexChannelConfig) DeepCopyInto(out *ImexChannelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImexChannelConfig.
func (in *ImexChannelConfig) DeepCopy() *ImexChannelConfig {
	if in == nil {
		return nil
	}
	out := new(ImexChannelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImexChannelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImexDaemonConfig) DeepCopyInto(out *ImexDaemonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImexDaemonConfig.
func (in *ImexDaemonConfig) DeepCopy() *ImexDaemonConfig {
	if in == nil {
		return nil
	}
	out := new(ImexDaemonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImexDaemonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigDeviceConfig) DeepCopyInto(out *MigDeviceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(MigDeviceSharing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigDeviceConfig.
func (in *MigDeviceConfig) DeepCopy() *MigDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(MigDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigDeviceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigDeviceSharing) DeepCopyInto(out *MigDeviceSharing) {
	*out = *in
	if in.MpsConfig != nil {
		in, out := &in.MpsConfig, &out.MpsConfig
		*out = new(MpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigDeviceSharing.
func (in *MigDeviceSharing) DeepCopy() *MigDeviceSharing {
	if in == nil {
		return nil
	}
	out := new(MigDeviceSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MpsConfig) DeepCopyInto(out *MpsConfig) {
	*out = *in
	if in.DefaultActiveThreadPercentage != nil {
		in, out := &in.DefaultActiveThreadPercentage, &out.DefaultActiveThreadPercentage
		*out = new(int)
		**out = **in
	}
	if in.DefaultPinnedDeviceMemoryLimit != nil {
		in, out := &in.DefaultPinnedDeviceMemoryLimit, &out.DefaultPinnedDeviceMemoryLimit
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DefaultPerDevicePinnedMemoryLimit != nil {
		in, out := &in.DefaultPerDevicePinnedMemoryLimit, &out.DefaultPerDevicePinnedMemoryLimit
		*out = make(MpsPerDevicePinnedMemoryLimit, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MpsConfig.
func (in *MpsConfig) DeepCopy() *MpsConfig {
	if in == nil {
		return nil
	}
	out := new(MpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MpsPerDevicePinnedMemoryLimit) DeepCopyInto(out *MpsPerDevicePinnedMemoryLimit) {
	{
		in := &in
		*out = make(MpsPerDevicePinnedMemoryLimit, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MpsPerDevicePinnedMemoryLimit.
func (in MpsPerDevicePinnedMemoryLimit) DeepCopy() MpsPerDevicePinnedMemoryLimit {
	if in == nil {
		return nil
	}
	out := new(MpsPerDevicePinnedMemoryLimit)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfig) DeepCopyInto(out *TimeSlicingConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(TimeSliceInterval)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfig.
func (in *TimeSlicingConfig) DeepCopy() *TimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}
