/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGpuParameterSets implements GpuParameterSetInterface
type FakeGpuParameterSets struct {
	Fake *FakeDraV1
	ns   string
}

var gpuparametersetsResource = schema.GroupVersionResource{Group: "dra.nvidia.com", Version: "v1", Resource: "gpuparametersets"}

var gpuparametersetsKind = schema.GroupVersionKind{Group: "dra.nvidia.com", Version: "v1", Kind: "GpuParameterSet"}

// Get takes name of the gpuParameterSet, and returns the corresponding gpuParameterSet object, and an error if there is any.
func (c *FakeGpuParameterSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.GpuParameterSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpuparametersetsResource, c.ns, name), &nvidiav1.GpuParameterSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuParameterSet), err
}

// List takes label and field selectors, and returns the list of GpuParameterSets that match those selectors.
func (c *FakeGpuParameterSets) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GpuParameterSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpuparametersetsResource, gpuparametersetsKind, c.ns, opts), &nvidiav1.GpuParameterSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GpuParameterSetList{ListMeta: obj.(*nvidiav1.GpuParameterSetList).ListMeta}
	for _, item := range obj.(*nvidiav1.GpuParameterSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gpuParameterSets.
func (c *FakeGpuParameterSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpuparametersetsResource, c.ns, opts))

}

// Create takes the representation of a gpuParameterSet and creates it.  Returns the server's representation of the gpuParameterSet, and an error, if there is any.
func (c *FakeGpuParameterSets) Create(ctx context.Context, gpuParameterSet *nvidiav1.GpuParameterSet, opts v1.CreateOptions) (result *nvidiav1.GpuParameterSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpuparametersetsResource, c.ns, gpuParameterSet), &nvidiav1.GpuParameterSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuParameterSet), err
}

// Update takes the representation of a gpuParameterSet and updates it. Returns the server's representation of the gpuParameterSet, and an error, if there is any.
func (c *FakeGpuParameterSets) Update(ctx context.Context, gpuParameterSet *nvidiav1.GpuParameterSet, opts v1.UpdateOptions) (result *nvidiav1.GpuParameterSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpuparametersetsResource, c.ns, gpuParameterSet), &nvidiav1.GpuParameterSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuParameterSet), err
}

// Delete takes name of the gpuParameterSet and deletes it. Returns an error if one occurs.
func (c *FakeGpuParameterSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpuparametersetsResource, c.ns, name, opts), &nvidiav1.GpuParameterSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGpuParameterSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpuparametersetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GpuParameterSetList{})
	return err
}

// Patch applies the patch and returns the patched gpuParameterSet.
func (c *FakeGpuParameterSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.GpuParameterSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuparametersetsResource, c.ns, name, pt, data, subresources...), &nvidiav1.GpuParameterSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuParameterSet), err
}
