/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGpus implements GpuInterface
type FakeGpus struct {
	Fake *FakeDraV1
	ns   string
}

var gpusResource = schema.GroupVersionResource{Group: "dra.nvidia.com", Version: "v1", Resource: "gpus"}

var gpusKind = schema.GroupVersionKind{Group: "dra.nvidia.com", Version: "v1", Kind: "Gpu"}

// Get takes name of the gpu, and returns the corresponding gpu object, and an error if there is any.
func (c *FakeGpus) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.Gpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpusResource, c.ns, name), &nvidiav1.Gpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.Gpu), err
}

// List takes label and field selectors, and returns the list of Gpus that match those selectors.
func (c *FakeGpus) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GpuList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpusResource, gpusKind, c.ns, opts), &nvidiav1.GpuList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GpuList{ListMeta: obj.(*nvidiav1.GpuList).ListMeta}
	for _, item := range obj.(*nvidiav1.GpuList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gpus.
func (c *FakeGpus) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpusResource, c.ns, opts))

}

// Create takes the representation of a gpu and creates it.  Returns the server's representation of the gpu, and an error, if there is any.
func (c *FakeGpus) Create(ctx context.Context, gpu *nvidiav1.Gpu, opts v1.CreateOptions) (result *nvidiav1.Gpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpusResource, c.ns, gpu), &nvidiav1.Gpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.Gpu), err
}

// Update takes the representation of a gpu and updates it. Returns the server's representation of the gpu, and an error, if there is any.
func (c *FakeGpus) Update(ctx context.Context, gpu *nvidiav1.Gpu, opts v1.UpdateOptions) (result *nvidiav1.Gpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpusResource, c.ns, gpu), &nvidiav1.Gpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.Gpu), err
}

// Delete takes name of the gpu and deletes it. Returns an error if one occurs.
func (c *FakeGpus) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpusResource, c.ns, name, opts), &nvidiav1.Gpu{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGpus) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpusResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GpuList{})
	return err
}

// Patch applies the patch and returns the patched gpu.
func (c *FakeGpus) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.Gpu, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpusResource, c.ns, name, pt, data, subresources...), &nvidiav1.Gpu{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.Gpu), err
}
