/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGpuClaimParameters implements GpuClaimParametersInterface
type FakeGpuClaimParameters struct {
	Fake *FakeDraV1
	ns   string
}

var gpuclaimparametersResource = schema.GroupVersionResource{Group: "dra.gpu.nvidia.com", Version: "v1", Resource: "gpuclaimparameters"}

var gpuclaimparametersKind = schema.GroupVersionKind{Group: "dra.gpu.nvidia.com", Version: "v1", Kind: "GpuClaimParameters"}

// Get takes name of the gpuClaimParameters, and returns the corresponding gpuClaimParameters object, and an error if there is any.
func (c *FakeGpuClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.GpuClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpuclaimparametersResource, c.ns, name), &nvidiav1.GpuClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaimParameters), err
}

// List takes label and field selectors, and returns the list of GpuClaimParameters that match those selectors.
func (c *FakeGpuClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GpuClaimParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpuclaimparametersResource, gpuclaimparametersKind, c.ns, opts), &nvidiav1.GpuClaimParametersList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GpuClaimParametersList{ListMeta: obj.(*nvidiav1.GpuClaimParametersList).ListMeta}
	for _, item := range obj.(*nvidiav1.GpuClaimParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gpuClaimParameters.
func (c *FakeGpuClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpuclaimparametersResource, c.ns, opts))

}

// Create takes the representation of a gpuClaimParameters and creates it.  Returns the server's representation of the gpuClaimParameters, and an error, if there is any.
func (c *FakeGpuClaimParameters) Create(ctx context.Context, gpuClaimParameters *nvidiav1.GpuClaimParameters, opts v1.CreateOptions) (result *nvidiav1.GpuClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpuclaimparametersResource, c.ns, gpuClaimParameters), &nvidiav1.GpuClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaimParameters), err
}

// Update takes the representation of a gpuClaimParameters and updates it. Returns the server's representation of the gpuClaimParameters, and an error, if there is any.
func (c *FakeGpuClaimParameters) Update(ctx context.Context, gpuClaimParameters *nvidiav1.GpuClaimParameters, opts v1.UpdateOptions) (result *nvidiav1.GpuClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpuclaimparametersResource, c.ns, gpuClaimParameters), &nvidiav1.GpuClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaimParameters), err
}

// Delete takes name of the gpuClaimParameters and deletes it. Returns an error if one occurs.
func (c *FakeGpuClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpuclaimparametersResource, c.ns, name, opts), &nvidiav1.GpuClaimParameters{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGpuClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpuclaimparametersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GpuClaimParametersList{})
	return err
}

// Patch applies the patch and returns the patched gpuClaimParameters.
func (c *FakeGpuClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.GpuClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuclaimparametersResource, c.ns, name, pt, data, subresources...), &nvidiav1.GpuClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaimParameters), err
}
