/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeComputeInstanceClaims implements ComputeInstanceClaimInterface
type FakeComputeInstanceClaims struct {
	Fake *FakeDraV1
	ns   string
}

var computeinstanceclaimsResource = schema.GroupVersionResource{Group: "dra.gpu.nvidia.com", Version: "v1", Resource: "computeinstanceclaims"}

var computeinstanceclaimsKind = schema.GroupVersionKind{Group: "dra.gpu.nvidia.com", Version: "v1", Kind: "ComputeInstanceClaim"}

// Get takes name of the computeInstanceClaim, and returns the corresponding computeInstanceClaim object, and an error if there is any.
func (c *FakeComputeInstanceClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.ComputeInstanceClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(computeinstanceclaimsResource, c.ns, name), &nvidiav1.ComputeInstanceClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.ComputeInstanceClaim), err
}

// List takes label and field selectors, and returns the list of ComputeInstanceClaims that match those selectors.
func (c *FakeComputeInstanceClaims) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.ComputeInstanceClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(computeinstanceclaimsResource, computeinstanceclaimsKind, c.ns, opts), &nvidiav1.ComputeInstanceClaimList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.ComputeInstanceClaimList{ListMeta: obj.(*nvidiav1.ComputeInstanceClaimList).ListMeta}
	for _, item := range obj.(*nvidiav1.ComputeInstanceClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeInstanceClaims.
func (c *FakeComputeInstanceClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(computeinstanceclaimsResource, c.ns, opts))

}

// Create takes the representation of a computeInstanceClaim and creates it.  Returns the server's representation of the computeInstanceClaim, and an error, if there is any.
func (c *FakeComputeInstanceClaims) Create(ctx context.Context, computeInstanceClaim *nvidiav1.ComputeInstanceClaim, opts v1.CreateOptions) (result *nvidiav1.ComputeInstanceClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(computeinstanceclaimsResource, c.ns, computeInstanceClaim), &nvidiav1.ComputeInstanceClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.ComputeInstanceClaim), err
}

// Update takes the representation of a computeInstanceClaim and updates it. Returns the server's representation of the computeInstanceClaim, and an error, if there is any.
func (c *FakeComputeInstanceClaims) Update(ctx context.Context, computeInstanceClaim *nvidiav1.ComputeInstanceClaim, opts v1.UpdateOptions) (result *nvidiav1.ComputeInstanceClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(computeinstanceclaimsResource, c.ns, computeInstanceClaim), &nvidiav1.ComputeInstanceClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.ComputeInstanceClaim), err
}

// Delete takes name of the computeInstanceClaim and deletes it. Returns an error if one occurs.
func (c *FakeComputeInstanceClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(computeinstanceclaimsResource, c.ns, name, opts), &nvidiav1.ComputeInstanceClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeInstanceClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(computeinstanceclaimsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.ComputeInstanceClaimList{})
	return err
}

// Patch applies the patch and returns the patched computeInstanceClaim.
func (c *FakeComputeInstanceClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.ComputeInstanceClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(computeinstanceclaimsResource, c.ns, name, pt, data, subresources...), &nvidiav1.ComputeInstanceClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.ComputeInstanceClaim), err
}
