/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGpuClaims implements GpuClaimInterface
type FakeGpuClaims struct {
	Fake *FakeDraV1
	ns   string
}

var gpuclaimsResource = schema.GroupVersionResource{Group: "dra.gpu.nvidia.com", Version: "v1", Resource: "gpuclaims"}

var gpuclaimsKind = schema.GroupVersionKind{Group: "dra.gpu.nvidia.com", Version: "v1", Kind: "GpuClaim"}

// Get takes name of the gpuClaim, and returns the corresponding gpuClaim object, and an error if there is any.
func (c *FakeGpuClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *nvidiav1.GpuClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpuclaimsResource, c.ns, name), &nvidiav1.GpuClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaim), err
}

// List takes label and field selectors, and returns the list of GpuClaims that match those selectors.
func (c *FakeGpuClaims) List(ctx context.Context, opts v1.ListOptions) (result *nvidiav1.GpuClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpuclaimsResource, gpuclaimsKind, c.ns, opts), &nvidiav1.GpuClaimList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nvidiav1.GpuClaimList{ListMeta: obj.(*nvidiav1.GpuClaimList).ListMeta}
	for _, item := range obj.(*nvidiav1.GpuClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gpuClaims.
func (c *FakeGpuClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpuclaimsResource, c.ns, opts))

}

// Create takes the representation of a gpuClaim and creates it.  Returns the server's representation of the gpuClaim, and an error, if there is any.
func (c *FakeGpuClaims) Create(ctx context.Context, gpuClaim *nvidiav1.GpuClaim, opts v1.CreateOptions) (result *nvidiav1.GpuClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpuclaimsResource, c.ns, gpuClaim), &nvidiav1.GpuClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaim), err
}

// Update takes the representation of a gpuClaim and updates it. Returns the server's representation of the gpuClaim, and an error, if there is any.
func (c *FakeGpuClaims) Update(ctx context.Context, gpuClaim *nvidiav1.GpuClaim, opts v1.UpdateOptions) (result *nvidiav1.GpuClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpuclaimsResource, c.ns, gpuClaim), &nvidiav1.GpuClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaim), err
}

// Delete takes name of the gpuClaim and deletes it. Returns an error if one occurs.
func (c *FakeGpuClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpuclaimsResource, c.ns, name, opts), &nvidiav1.GpuClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGpuClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpuclaimsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nvidiav1.GpuClaimList{})
	return err
}

// Patch applies the patch and returns the patched gpuClaim.
func (c *FakeGpuClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1.GpuClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuclaimsResource, c.ns, name, pt, data, subresources...), &nvidiav1.GpuClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nvidiav1.GpuClaim), err
}
