/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/NVIDIA/k8s-dra-driver/api/nvidia.com/resource/gpu/v1alpha1"
	scheme "github.com/NVIDIA/k8s-dra-driver/pkg/nvidia.com/resource/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GpuClaimParametersGetter has a method to return a GpuClaimParametersInterface.
// A group's client should implement this interface.
type GpuClaimParametersGetter interface {
	GpuClaimParameters(namespace string) GpuClaimParametersInterface
}

// GpuClaimParametersInterface has methods to work with GpuClaimParameters resources.
type GpuClaimParametersInterface interface {
	Create(ctx context.Context, gpuClaimParameters *v1alpha1.GpuClaimParameters, opts v1.CreateOptions) (*v1alpha1.GpuClaimParameters, error)
	Update(ctx context.Context, gpuClaimParameters *v1alpha1.GpuClaimParameters, opts v1.UpdateOptions) (*v1alpha1.GpuClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GpuClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GpuClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GpuClaimParameters, err error)
	GpuClaimParametersExpansion
}

// gpuClaimParameters implements GpuClaimParametersInterface
type gpuClaimParameters struct {
	client rest.Interface
	ns     string
}

// newGpuClaimParameters returns a GpuClaimParameters
func newGpuClaimParameters(c *GpuV1alpha1Client, namespace string) *gpuClaimParameters {
	return &gpuClaimParameters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gpuClaimParameters, and returns the corresponding gpuClaimParameters object, and an error if there is any.
func (c *gpuClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GpuClaimParameters, err error) {
	result = &v1alpha1.GpuClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GpuClaimParameters that match those selectors.
func (c *gpuClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GpuClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GpuClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gpuClaimParameters.
func (c *gpuClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gpuClaimParameters and creates it.  Returns the server's representation of the gpuClaimParameters, and an error, if there is any.
func (c *gpuClaimParameters) Create(ctx context.Context, gpuClaimParameters *v1alpha1.GpuClaimParameters, opts v1.CreateOptions) (result *v1alpha1.GpuClaimParameters, err error) {
	result = &v1alpha1.GpuClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gpuClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gpuClaimParameters and updates it. Returns the server's representation of the gpuClaimParameters, and an error, if there is any.
func (c *gpuClaimParameters) Update(ctx context.Context, gpuClaimParameters *v1alpha1.GpuClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.GpuClaimParameters, err error) {
	result = &v1alpha1.GpuClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(gpuClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gpuClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gpuClaimParameters and deletes it. Returns an error if one occurs.
func (c *gpuClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gpuClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gpuClaimParameters.
func (c *gpuClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GpuClaimParameters, err error) {
	result = &v1alpha1.GpuClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
