# MPSC-Unshared-GPU: multiple pods, each with a single container, request dedicated access to a GPU.
# 
# One pod will be running and the other one will be pending.
# $ kubectl get pods -n mpsc-unshared-gpu-test
# NAME        READY   STATUS    RESTARTS      AGE
# gpu-pod-1   1/1     Running   1 (21s ago)   58s
# gpu-pod-2   0/1     Pending   0             25s
#
# Running the command `nvidia-smi` will show something like the following:
# +---------------------------------------------------------------------------------------+
# | Processes:                                                                            |
# |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
# |        ID   ID                                                             Usage      |
# |    0   N/A  N/A   1544488      C   /cuda-samples/sample                    746MiB     |
# |=======================================================================================|

---
apiVersion: v1
kind: Namespace
metadata:
  name: mpsc-unshared-gpu-test

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: mpsc-unshared-gpu-test
  name: gpu.nvidia.com
spec:
  spec:
    resourceClassName: gpu.nvidia.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: mpsc-unshared-gpu-test
  name: gpu-pod-1
  labels:
    app: pod
spec:
  containers:
  - name: ctr
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    source:
      resourceClaimTemplateName: gpu.nvidia.com
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  namespace: mpsc-unshared-gpu-test
  name: gpu-pod-2
  labels:
    app: pod
spec:
  containers:
  - name: ctr
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    source:
      resourceClaimTemplateName: gpu.nvidia.com
  restartPolicy: Never
