# SPMC-MPS-GPU: a single pod's multiple containers share a GPU via MPS.

# The pod will be running.
# $ kubectl get pods -n spmc-mps-gpu-test
# NAME      READY   STATUS    RESTARTS   AGE
# gpu-pod   2/2     Running   0          8s

# Run `nvidia-smi` will show something like the following:
# +---------------------------------------------------------------------------------------+
# | Processes:                                                                            |
# |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
# |        ID   ID                                                             Usage      |
# |=======================================================================================|
# |    0   N/A  N/A   1559554    M+C   /cuda-samples/sample                        790MiB |
# |    0   N/A  N/A   1559585      C   nvidia-cuda-mps-server                       28MiB |
# |    0   N/A  N/A   1559610    M+C   /cuda-samples/sample                        790MiB |
# +---------------------------------------------------------------------------------------+

---
apiVersion: v1
kind: Namespace
metadata:
  name: spmc-mps-gpu-test

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  namespace: spmc-mps-gpu-test
  name: gpu-mps-sharing
spec:
  resourceClassName: gpu.nvidia.com
  parametersRef:
    apiGroup: gpu.resource.nvidia.com
    kind: GpuClaimParameters
    name: gpu-mps-sharing

---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: GpuClaimParameters
metadata:
  namespace: spmc-mps-gpu-test
  name: gpu-mps-sharing
spec:
  sharing:
    strategy: MPS
    mpsConfig:
      defaultActiveThreadPercentage: 50
      defaultPinnedDeviceMemoryLimit: 10Gi
      # defaultPerDevicePinnedMemoryLimit:
      #   0: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  namespace: spmc-mps-gpu-test
  name: gpu-pod
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu
  - name: ctr1
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    source:
      resourceClaimName: gpu-mps-sharing
  restartPolicy: Never
