/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/clientset/versioned"
	internalinterfaces "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/informers/externalversions/internalinterfaces"
	v1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/listers/nvidia/v1"
	nvidiav1 "github.com/NVIDIA/k8s-dra-driver/pkg/crd/nvidia/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GpuParameterSetInformer provides access to a shared informer and lister for
// GpuParameterSets.
type GpuParameterSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GpuParameterSetLister
}

type gpuParameterSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGpuParameterSetInformer constructs a new informer for GpuParameterSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGpuParameterSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGpuParameterSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGpuParameterSetInformer constructs a new informer for GpuParameterSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGpuParameterSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1().GpuParameterSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1().GpuParameterSets(namespace).Watch(context.TODO(), options)
			},
		},
		&nvidiav1.GpuParameterSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *gpuParameterSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGpuParameterSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gpuParameterSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nvidiav1.GpuParameterSet{}, f.defaultInformer)
}

func (f *gpuParameterSetInformer) Lister() v1.GpuParameterSetLister {
	return v1.NewGpuParameterSetLister(f.Informer().GetIndexer())
}
