---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Namespace }}
  generateName: {{ .GenerateName }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    {{ .MultiNodeEnvironmentLabelKey }}: {{ .MultiNodeEnvironmentLabelValue }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      {{ .MultiNodeEnvironmentLabelKey }}: {{ .MultiNodeEnvironmentLabelValue }}
  template:
    metadata:
      labels:
        {{ .MultiNodeEnvironmentLabelKey }}: {{ .MultiNodeEnvironmentLabelValue }}
    spec:
      hostNetwork: true
      containers:
      - name: imex-daemon
        image: ubuntu:22.04
        command: [chroot, /driver-root, sh, -c]
        args:
        - |-
          set -e
          rm -f /var/log/nvidia-imex.log
          /usr/bin/nvidia-imex -c /etc/nvidia-imex/config.cfg
          trap 'exit 0' TERM
          tail -n +1 -f /var/log/nvidia-imex.log & wait
        startupProbe:
          exec:
            command:
            - cat
            - /driver-root/var/log/nvidia-imex.log
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        securityContext:
          privileged: true
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: {{ .MultiNodeEnvironmentLabelKey }}
                  operator: In
                  values:
                  - {{ .MultiNodeEnvironmentLabelValue }}
              topologyKey: "nvidia.com/gpu.clique"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: {{ .MultiNodeEnvironmentLabelKey }}
                  operator: In
                  values:
                  - {{ .MultiNodeEnvironmentLabelValue }}
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: driver-root
        hostPath:
          path: {{ .NvidiaDriverRoot }}
