---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .MpsControlDaemonNamespace }}
  name: {{ .MpsControlDaemonName }}
  labels:
    app: {{ .MpsControlDaemonName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .MpsControlDaemonName }}
  template:
    metadata:
      labels:
        app: {{ .MpsControlDaemonName }}
    spec:
      nodeName: {{ .NodeName }}
      hostPID: true
      containers:
      - name: mps-control-daemon
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command: [chroot, /driver-root, sh, -c]
        args:
        - |-
          set -e
          rm -f /var/log/nvidia-mps/startup.log

          nvidia-cuda-mps-control -d
          {{- if .DefaultActiveThreadPercentage }}
          echo set_default_active_thread_percentage {{.DefaultActiveThreadPercentage}} | nvidia-cuda-mps-control
          {{- end}}
          {{- range $id, $limit := .DefaultPinnedDeviceMemoryLimits }}
          echo set_default_device_pinned_mem_limit {{ $id }} {{ $limit }} | nvidia-cuda-mps-control
          {{- end}}

          echo "startup complete" > /var/log/nvidia-mps/startup.log

          tail -n +1 -f /var/log/nvidia-mps/control.log
        startupProbe:
          exec:
            command:
            - cat
            - /driver-root/var/log/nvidia-mps/startup.log
          initialDelaySeconds: 1
          periodSeconds: 1
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "{{ .CUDA_VISIBLE_DEVICES }}"
        volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        - name: mps-shm-directory
          mountPath: /driver-root/dev/shm
        - name: mps-pipe-directory
          mountPath: /driver-root/tmp/nvidia-mps
        - name: mps-log-directory
          mountPath: /driver-root/var/log/nvidia-mps
      volumes:
      - name: driver-root
        hostPath:
          path: {{ .NvidiaDriverRoot }}
      - name: mps-shm-directory
        hostPath:
          path: {{ .MpsShmDirectory }}
      - name: mps-pipe-directory
        hostPath:
          path: {{ .MpsPipeDirectory }}
      - name: mps-log-directory
        hostPath:
          path: {{ .MpsLogDirectory }}
