# One pod, 4 containers
# Each asking for a different MIG device on a shared mig-enabled GPU
# Run as deployment with 4 replicas

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test4

---
apiVersion: dra.gpu.nvidia.com/v1
kind: GpuClaimParameters
metadata:
  namespace: gpu-test4
  name: mig-enabled-gpu
spec:
  count: 1
  migEnabled: true

---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test4
  name: mig-enabled-gpu
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: dra.gpu.nvidia.com
      kind: GpuClaimParameters
      name: mig-enabled-gpu

---
apiVersion: dra.gpu.nvidia.com/v1
kind: MigDeviceClaimParameters
metadata:
  namespace: gpu-test4
  name: mig-1g.5gb
spec:
  profile: "1g.5gb"
  gpuClaimName: "mig-enabled-gpu"

---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test4
  name: mig-1g.5gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: dra.gpu.nvidia.com
      kind: MigDeviceClaimParameters
      name: mig-1g.5gb

---
apiVersion: dra.gpu.nvidia.com/v1
kind: MigDeviceClaimParameters
metadata:
  namespace: gpu-test4
  name: mig-2g.10gb
spec:
  profile: "2g.10gb"
  gpuClaimName: "mig-enabled-gpu"

---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test4
  name: mig-2g.10gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: dra.gpu.nvidia.com
      kind: MigDeviceClaimParameters
      name: mig-2g.10gb

---
apiVersion: dra.gpu.nvidia.com/v1
kind: MigDeviceClaimParameters
metadata:
  namespace: gpu-test4
  name: mig-3g.20gb
spec:
  profile: "3g.20gb"
  gpuClaimName: "mig-enabled-gpu"

---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test4
  name: mig-3g.20gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: dra.gpu.nvidia.com
      kind: MigDeviceClaimParameters
      name: mig-3g.20gb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpu-test4
  name: pod
  labels:
    app: gpu-test4-pod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      resourceClaims:
      - name: mig-enabled-gpu
        source:
          resourceClaimTemplateName: mig-enabled-gpu
      - name: mig-1g-0
        source:
          resourceClaimTemplateName: mig-1g.5gb
      - name: mig-1g-1
        source:
          resourceClaimTemplateName: mig-1g.5gb
      - name: mig-2g
        source:
          resourceClaimTemplateName: mig-2g.10gb
      - name: mig-3g
        source:
          resourceClaimTemplateName: mig-3g.20gb
      containers:
      - name: ctr0
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: mig-enabled-gpu
          - name: mig-3g
      - name: ctr1
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: mig-enabled-gpu
          - name: mig-2g
      - name: ctr2
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: mig-enabled-gpu
          - name: mig-1g-0
      - name: ctr3
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: mig-enabled-gpu
          - name: mig-1g-1
