# One pod, 2 containers
# Each asking for a compute slice of a shared MIG device
# Run as deployment with 6 replicas

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test5

---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: MigDeviceClaimParameters
metadata:
  namespace: gpu-test5
  name: shared-2g.10gb
spec:
  profile: "2g.10gb"
  uninitialized: true

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test5
  name: shared-2g.10gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: gpu.resource.nvidia.com
      kind: MigDeviceClaimParameters
      name: shared-2g.10gb

---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: ComputeInstanceClaimParameters
metadata:
  namespace: gpu-test5
  name: 1c.2g.10gb
spec:
  profile: "1c.2g.10gb"
  migDeviceClaimName: "shared-2g.10gb"

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test5
  name: 1c.2g.10gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: gpu.resource.nvidia.com
      kind: ComputeInstanceClaimParameters
      name: 1c.2g.10gb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpu-test5
  name: pod
  labels:
    app: gpu-test5-pod
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: ctr0
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: shared-2g
          - name: 1c-0
      - name: ctr1
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: shared-2g
          - name: 1c-1
      resourceClaims:
      - name: shared-2g
        source:
          resourceClaimTemplateName: shared-2g.10gb
      - name: 1c-0
        source:
          resourceClaimTemplateName: 1c.2g.10gb
      - name: 1c-1
        source:
          resourceClaimTemplateName: 1c.2g.10gb
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
