# One pod, 4 containers
# Each asking for a different MIG device on a shared mig-enabled GPU
# Run as deployment with 4 replicas

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test6

---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: GpuClaimParameters
metadata:
  namespace: gpu-test6
  name: a100
spec:
  count: 1
  selector:
    andExpression:
    - productName: "*a100*"
    - orExpression:
      - index: 0
      - index: 2
      - index: 4
      - index: 6
    - orExpression:
      - migEnabled: true
      - migEnabled: false

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test6
  name: a100
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: gpu.resource.nvidia.com
      kind: GpuClaimParameters
      name: a100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpu-test6
  name: pod
  labels:
    app: gpu-test6-pod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      resourceClaims:
      - name: a100
        source:
          resourceClaimTemplateName: a100
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; sleep 9999"]
        resources:
          claims:
          - name: a100
