/*
 * Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	"github.com/NVIDIA/k8s-dra-driver/pkg/nvidia.com/api/resource/gpu/clientset/versioned/scheme"
	v1alpha1 "github.com/NVIDIA/k8s-dra-driver/pkg/nvidia.com/api/resource/gpu/v1alpha1"
	rest "k8s.io/client-go/rest"
)

type GpuV1alpha1Interface interface {
	RESTClient() rest.Interface
	ComputeInstanceClaimParametersesGetter
	DeviceClassParametersGetter
	GpuClaimParametersGetter
	MigDeviceClaimParametersGetter
	NodeAllocationStatesGetter
}

// GpuV1alpha1Client is used to interact with features provided by the gpu.resource.nvidia.com group.
type GpuV1alpha1Client struct {
	restClient rest.Interface
}

func (c *GpuV1alpha1Client) ComputeInstanceClaimParameterses(namespace string) ComputeInstanceClaimParametersInterface {
	return newComputeInstanceClaimParameterses(c, namespace)
}

func (c *GpuV1alpha1Client) DeviceClassParameters() DeviceClassParametersInterface {
	return newDeviceClassParameters(c)
}

func (c *GpuV1alpha1Client) GpuClaimParameters(namespace string) GpuClaimParametersInterface {
	return newGpuClaimParameters(c, namespace)
}

func (c *GpuV1alpha1Client) MigDeviceClaimParameters(namespace string) MigDeviceClaimParametersInterface {
	return newMigDeviceClaimParameters(c, namespace)
}

func (c *GpuV1alpha1Client) NodeAllocationStates(namespace string) NodeAllocationStateInterface {
	return newNodeAllocationStates(c, namespace)
}

// NewForConfig creates a new GpuV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*GpuV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new GpuV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*GpuV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &GpuV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new GpuV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *GpuV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new GpuV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *GpuV1alpha1Client {
	return &GpuV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *GpuV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
